[project]
name = "Latin_scansion_with_neural_networks"
version = "1.0.0"
description = "In this project we try to teach a neural network to scan Latin poetry"
requires-python = ">=3.12"

dependencies = [
  # rtcompat for my old machine
  "polars[rtcompat]",
  "torch",
  "pytorch-crf",
  "tensorflow",
  "scikit-learn",
  "seaborn",
  "matplotlib",
  "pandas",
  "pudb",
  "tqdm",
  "mqdqparser>=0.6.2",
  "ipython<9.0",
  "unidecode>=1.4.0",
]

